apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-trading-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-trading-platform
  template:
    metadata:
      labels:
        app: stock-trading-platform
    spec:
      containers:
      - name: stock-trading-platform
        image: busybox  # Placeholder image
        command: ["sleep", "3600"]  # Keeps the container running
        ports:
        - containerPort: 8000
